### ISSUE TITLE
Feature 1: Handling tie in the game

### ISSUE THREAD

**Issue by ghaemisr** [ghaemisr/tictactoe#1]
There is currently no check if there is a tie in the game (i.e., there is no longer a chance for either player X or O to win). We need to implement such functionality, where after a move, a message will notify the player if the game is in a tie and will end the game.

**Comment by ghaemisr** [comment]
To address this issue I added a function to the Board class that shows whether the board is full or not. This function is called boardIsFull which returns a boolean. Then I used this function in the playGame function to handle the tie situation.

**Comment by ghaemisr** [comment]
@linncy Let me know if you needed anything in this code or if you had a hard time using it.

**Comment by linncy** [comment]
When the game ends up in a tie, please assign winner the value Player.NONE.
By doing so, it would be easy for us to handle tie when we use the ScoreBoard class.
