### ISSUE TITLE
Feature 3: Multiple games 

### ISSUE THREAD

**Issue by ghaemisr** [ghaemisr/tictactoe#7]
The game currently ends whenever a player wins. We should change the code so that when a game ends it asks the users if they want to play again. If yes the program should start a new game. If no the program should show the score board and then terminate.

**Comment by ghaemisr** [comment]
To solve this issue I added the following methods to TicTacToeGame class:

1. **public char prompt()**:
This method asks the user if they want to play the game again or not. Finally, it returns the answer as a character. 

2. **public void playMultipleGames()**:
This method uses the answer from prompt method to run the game multiple times.

**Comment by ghaemisr** [comment]
@linncy Do we show the game scoreboard after each game or at the end of all the games?

**Comment by linncy** [comment]
Please make it show at the end of all the games. @ghaemisr
